# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ff774ac748aa2a2c77c7c623488e57af0aa6d075c88be6f9bf1c67b79e724085fcaa14695d17b1ee0d81917f113accea3acc3309989c782d191879d6fd992da

test:
  secret_key_base: e724a2fb56f18e95c4651c88c247845cc08a27580677ce3372bc1ca0c14a0a23a5ea448393878d753592ead4ea3c6ae892d06f9466b4ab96da7191f43a211bf7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
